### PR TITLE
Make TypeScript a peerDependency

### PR DESCRIPTION
**Pull request by oeb25**
Make TypeScript a peerDependency instead of a static dependency to allow user defined TypeScirpt versions

### CODE REVIEW

**Comment by schulzch** [comment]
Seems like a _very good_ idea!

**Comment by paulmedynski** [comment]
I have typescript-brunch 2.3.0 working with TypeScript 3.1.0.  I literally just deleted the typescript/ dir in typescript-brunch/node_modules and symlinked to the typescript 3.1.0 folder.  Can we update the package.json in change to allow v2 and v3 of TypeScript as a peer dependency?

**Comment by paulmedynski** [comment]
Note that paulmillr noted (in another issue thread) that he (and his colleagues?) aren't actively working on Brunch at all currently, so I doubt he'll have time to review this change.  Are there other maintainers who can review and merge this?

**Comment by paulmillr** [comment]
@paulmedynski added you as a collab

**Pull request merged**
